name: 'Release App'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            rust-target: 'aarch64-apple-darwin'
          - platform: 'macos-latest' 
            args: '--target x86_64-apple-darwin'
            rust-target: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            rust-target: ''
          - platform: 'windows-latest'
            args: ''
            rust-target: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # =================== SYSTEM DEPENDENCIES ===================
      
      - name: Install system dependencies (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libtesseract-dev \
            libleptonica-dev \
            tesseract-ocr \
            tesseract-ocr-eng
          # Verify Tesseract installation
          tesseract --version
          pkg-config --cflags --libs tesseract

      - name: Install system dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          # Install Tesseract via Homebrew
          brew install tesseract leptonica
          # Verify installation
          tesseract --version
          # Set environment variables for Rust compilation
          echo "TESSERACT_INCLUDE_PATHS=$(brew --prefix tesseract)/include" >> $GITHUB_ENV
          echo "TESSERACT_LINK_PATHS=$(brew --prefix tesseract)/lib" >> $GITHUB_ENV
          echo "LEPTONICA_INCLUDE_PATHS=$(brew --prefix leptonica)/include" >> $GITHUB_ENV
          echo "LEPTONICA_LINK_PATHS=$(brew --prefix leptonica)/lib" >> $GITHUB_ENV

      - name: Install system dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          # Install Tesseract via vcpkg
          vcpkg install tesseract:x64-windows-static-md leptonica:x64-windows-static-md
          # Set environment variables
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "TESSERACT_INCLUDE_PATHS=C:\vcpkg\installed\x64-windows-static-md\include" >> $env:GITHUB_ENV
          echo "TESSERACT_LINK_PATHS=C:\vcpkg\installed\x64-windows-static-md\lib" >> $env:GITHUB_ENV

      # =================== RUST SETUP ===================

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ matrix.platform }}-${{ matrix.rust-target }}

      # =================== NODE.JS SETUP ===================

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      # =================== TAURI BUILD ===================

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tesseract environment variables
          TESSERACT_INCLUDE_PATHS: ${{ env.TESSERACT_INCLUDE_PATHS }}
          TESSERACT_LINK_PATHS: ${{ env.TESSERACT_LINK_PATHS }}
          LEPTONICA_INCLUDE_PATHS: ${{ env.LEPTONICA_INCLUDE_PATHS }}
          LEPTONICA_LINK_PATHS: ${{ env.LEPTONICA_LINK_PATHS }}
          # Windows specific
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'FrameSense v__VERSION__'
          releaseBody: |
            🎉 **FrameSense v__VERSION__ is here!**
            
            ## ✨ What's New
            - AI-powered screen capture with instant insights
            - OCR text extraction from any screen content  
            - Smart contextual analysis using GPT-4 Vision
            - Lightning-fast native performance
            
            ## 📥 Download for your platform:
            - **macOS**: Download the `.dmg` file
            - **Windows**: Download the `.msi` file  
            - **Linux**: Download the `.AppImage` file
            
            ## 🚀 Quick Start
            1. Download the app for your platform
            2. Install and launch FrameSense
            3. Use the global shortcut to capture any screen area
            4. Ask questions about what you see!
            
            Built with ❤️ using Tauri + React + Rust
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: true 