name: 'Release App'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            rust-target: 'aarch64-apple-darwin'
          - platform: 'macos-latest' 
            args: '--target x86_64-apple-darwin'
            rust-target: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            rust-target: ''
          - platform: 'windows-latest'
            args: ''
            rust-target: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # =================== SYSTEM DEPENDENCIES ===================
      
      - name: Install system dependencies (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      # =================== RUST SETUP ===================

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ matrix.platform }}-${{ matrix.rust-target }}

      # =================== NODE.JS SETUP ===================

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      # =================== TAURI BUILD ===================

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'FrameSense v__VERSION__'
          releaseBody: |
            🎉 **FrameSense v__VERSION__ is here!**
            
            ## ✨ What's New
            - AI-powered screen capture with instant insights
            - Smart contextual analysis using GPT-4 Vision
            - Lightning-fast native performance
            - Note: OCR functionality available in local builds
            
            ## 📥 Download for your platform:
            - **macOS**: Download the `.dmg` file
            - **Windows**: Download the `.msi` file  
            - **Linux**: Download the `.AppImage` file
            
            ## 🚀 Quick Start
            1. Download the app for your platform
            2. Install and launch FrameSense
            3. Use the global shortcut to capture any screen area
            4. Ask questions about what you see!
            
            Built with ❤️ using Tauri + React + Rust
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: true 